%% Build the second-order adaptive DC-motor simulation model.
%
% Builds one self-contained Simulink model into ACE_OUT_DIR (default: pwd):
%   adaptive_dcmotor_2nd_sim.slx
%
% The model uses an exact ZOH-discretized second-order motor plant, a
% two-phase speed reference for excitation and tracking validation,
% 4-parameter RLS estimation and an RST controller with integral action
% from the fourth-order Diophantine pole-placement equation.
%
% Usage:
%   matlab.exe -wait -nosplash -sd <stage> -batch "build_second_order_model"

outDir = getenv('ACE_OUT_DIR');
if isempty(outDir), outDir = pwd; end

p = secondOrderParams();
buildSecondOrderSimModel(p, outDir);
disp('BUILD_OK');

%% ---------------------------------------------------------------- params
function p = secondOrderParams()
    p.Km = 0.05;
    p.J  = 0.001;
    p.b  = 0.0005;
    p.La = 0.002;
    p.Ra = 2.0;

    p.T       = 0.002;  % 2 ms - resolves the electrical pole
    p.alpha   = 1.0;    % no forgetting; alpha < 1 without PE causes P windup/bursting
    p.P0      = 100;    % P = P0 * eye(4)
    p.uMax    = 12;     % armature voltage limit [V]
    p.kFreeze = 50;     % apply pole placement only after 50 samples
    p.tEnd    = 8;      % simulation horizon [s]
    p.tPhase1 = 4;      % PRBS excitation horizon [s]

    p.refLow     = 60;
    p.refHigh    = 120;
    p.prbsHold   = 5;   % bit duration in samples, 5*T = 10 ms
    p.tracePLimit = 9000;

    p.pFast = 0.1357;   % electrical plant pole at T = 2 ms
    r = exp(-p.T / 0.05);
    % Design rule: modes much faster than the desired bandwidth are not
    % moved; otherwise the controller must invert the fast dynamics and can
    % become unstable, which necessarily diverges behind saturation.
    q = poly([0 p.pFast r r]);
    p.q3 = q(2);
    p.q2 = q(3);
    p.q1 = q(4);
    p.q0 = q(5);

    Gd = c2d(tf(p.Km, [p.La*p.J, p.La*p.b + p.Ra*p.J, p.Ra*p.b + p.Km^2]), ...
        p.T, 'zoh');
    [numd, dend] = tfdata(Gd, 'v');
    numd = numd / dend(1);
    dend = dend / dend(1);
    p.a1 = dend(end-1);
    p.a0 = dend(end);
    p.b1 = numd(end-1);
    p.b0 = numd(end);
end

function s = num(v)
    s = sprintf('%.10g', v);
end

function s = vec(v)
    s = ['[' strjoin(arrayfun(@num, v(:).', 'UniformOutput', false), ' ') ']'];
end

%% ------------------------------------------------ second-order simulation
function buildSecondOrderSimModel(p, outDir)
    mdl = 'adaptive_dcmotor_2nd_sim';
    if bdIsLoaded(mdl), close_system(mdl, 0); end
    new_system(mdl);
    set_param(mdl, ...
        'SolverType', 'Fixed-step', ...
        'Solver', 'FixedStepDiscrete', ...
        'FixedStep', num(p.T), ...
        'StopTime', num(p.tEnd), ...
        'SignalLogging', 'on', ...
        'SignalLoggingName', 'logsout', ...
        'Location', [100 100 1450 720]);

    refProfile = buildReferenceProfile(p);
    mdlWks = get_param(mdl, 'ModelWorkspace');
    assignin(mdlWks, 'refProfile', refProfile);

    add_block('simulink/Sources/From Workspace', [mdl '/Reference profile'], ...
        'VariableName', 'refProfile', ...
        'SampleTime', num(p.T), ...
        'Interpolate', 'off', ...
        'OutputAfterFinalValue', 'Holding final value', ...
        'Position', [45 105 155 145]);

    ctrl = [mdl '/Adaptive RST controller'];
    add_block('simulink/Ports & Subsystems/Subsystem', ctrl, ...
        'Position', [315 60 555 245]);
    Simulink.SubSystem.deleteContents(ctrl);
    buildControllerSubsystem(ctrl, p);

    add_block('simulink/Discrete/Discrete Transfer Fcn', [mdl '/ZOH motor plant'], ...
        'Numerator', vec([p.b1 p.b0]), ...
        'Denominator', vec([1 p.a1 p.a0]), ...
        'SampleTime', num(p.T), ...
        'Position', [640 105 760 165]);

    add_block('simulink/Signal Routing/Mux', [mdl '/Tracking mux'], ...
        'Inputs', '3', 'Position', [875 75 880 195]);
    add_block('simulink/Sinks/Scope', [mdl '/Tracking scope'], ...
        'Position', [940 105 990 155]);
    configureScope([mdl '/Tracking scope'], 1, true);

    add_block('simulink/Signal Routing/Mux', [mdl '/Parameter mux'], ...
        'Inputs', '4', 'Position', [875 300 880 430]);
    add_block('simulink/Sinks/Scope', [mdl '/Parameter scope'], ...
        'Position', [940 330 990 380]);
    configureScope([mdl '/Parameter scope'], 1, true);

    add_block('simulink/Sinks/Scope', [mdl '/Covariance scope'], ...
        'Position', [940 495 990 545]);
    configureScope([mdl '/Covariance scope'], 1, false);

    add_line(mdl, 'Reference profile/1', 'Adaptive RST controller/1', 'autorouting', 'on');
    add_line(mdl, 'Adaptive RST controller/1', 'ZOH motor plant/1', 'autorouting', 'on');
    add_line(mdl, 'ZOH motor plant/1', 'Adaptive RST controller/2', 'autorouting', 'on');

    add_line(mdl, 'Reference profile/1', 'Tracking mux/1', 'autorouting', 'on');
    add_line(mdl, 'ZOH motor plant/1', 'Tracking mux/2', 'autorouting', 'on');
    add_line(mdl, 'Adaptive RST controller/1', 'Tracking mux/3', 'autorouting', 'on');
    add_line(mdl, 'Tracking mux/1', 'Tracking scope/1', 'autorouting', 'on');

    add_line(mdl, 'Adaptive RST controller/2', 'Parameter mux/1', 'autorouting', 'on');
    add_line(mdl, 'Adaptive RST controller/3', 'Parameter mux/2', 'autorouting', 'on');
    add_line(mdl, 'Adaptive RST controller/4', 'Parameter mux/3', 'autorouting', 'on');
    add_line(mdl, 'Adaptive RST controller/5', 'Parameter mux/4', 'autorouting', 'on');
    add_line(mdl, 'Parameter mux/1', 'Parameter scope/1', 'autorouting', 'on');
    add_line(mdl, 'Adaptive RST controller/6', 'Covariance scope/1', 'autorouting', 'on');

    logSignal([mdl '/Reference profile'], 1, 'ref');
    logSignal([mdl '/ZOH motor plant'], 1, 'y');
    logSignal([mdl '/Adaptive RST controller'], 1, 'u');
    logSignal([mdl '/Adaptive RST controller'], 2, 'a1_est');
    logSignal([mdl '/Adaptive RST controller'], 3, 'a0_est');
    logSignal([mdl '/Adaptive RST controller'], 4, 'b1_est');
    logSignal([mdl '/Adaptive RST controller'], 5, 'b0_est');
    logSignal([mdl '/Adaptive RST controller'], 6, 'traceP');

    addNote(mdl, ['Second-order adaptive DC-motor simulation.' newline ...
        'Exact ZOH plant, T = ' num(p.T) ' s, PRBS reference 60/120 rad/s until ' ...
        num(p.tPhase1) ' s, then steps 90/130/90 rad/s.' newline ...
        'RLS theta = [a1; a0; b1; b0], P0 = ' num(p.P0) ...
        ', alpha = ' num(p.alpha) ', u in [' num(-p.uMax) ', ' num(p.uMax) '] V.'], [40 20]);
    addNote(mdl, ['True ZOH coefficients for y(k) + a1*y(k-1) + a0*y(k-2) = ' ...
        'b1*u(k-1) + b0*u(k-2):' newline ...
        'a1 = ' num(p.a1) ', a0 = ' num(p.a0) ...
        ', b1 = ' num(p.b1) ', b0 = ' num(p.b0) newline ...
        'Desired polynomial q(z) = z*(z - pFast)*(z - exp(-T/0.05))^2 = ' ...
        'z^4 + q3*z^3 + q2*z^2 + q1*z + q0.'], [40 580]);

    save_system(mdl, fullfile(outDir, [mdl '.slx']));
    close_system(mdl, 0);
    fprintf('Built %s\n', fullfile(outDir, [mdl '.slx']));
end

function refProfile = buildReferenceProfile(p)
    t = (0:p.T:p.tEnd).';
    ref = zeros(size(t));

    reg = ones(1, 7);
    holdCount = 0;
    level = p.refLow;
    for k = 1:numel(t)
        if t(k) < p.tPhase1
            if holdCount <= 0
                outBit = reg(7);
                newBit = double(xor(reg(7) > 0.5, reg(6) > 0.5));
                reg(7) = reg(6);
                reg(6) = reg(5);
                reg(5) = reg(4);
                reg(4) = reg(3);
                reg(3) = reg(2);
                reg(2) = reg(1);
                reg(1) = newBit;
                level = p.refLow + (p.refHigh - p.refLow) * outBit;
                holdCount = p.prbsHold;
            end
            ref(k) = level;
            holdCount = holdCount - 1;
        elseif t(k) < 5.5
            ref(k) = 90;
        elseif t(k) < 7.0
            ref(k) = 130;
        else
            ref(k) = 90;
        end
    end

    refProfile = [t, ref];
end

%% ------------------------------------------- shared controller subsystem
function buildControllerSubsystem(ctrl, p)
    T = num(p.T);
    add_block('simulink/Ports & Subsystems/In1', [ctrl '/reference'], ...
        'Port', '1', 'Position', [20 55 50 75]);
    add_block('simulink/Ports & Subsystems/In1', [ctrl '/speed'], ...
        'Port', '2', 'Position', [20 155 50 175]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/u_sat'], ...
        'Port', '1', 'Position', [820 55 850 75]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/a1_est'], ...
        'Port', '2', 'Position', [820 245 850 265]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/a0_est'], ...
        'Port', '3', 'Position', [820 285 850 305]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/b1_est'], ...
        'Port', '4', 'Position', [820 325 850 345]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/b0_est'], ...
        'Port', '5', 'Position', [820 365 850 385]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/traceP'], ...
        'Port', '6', 'Position', [820 425 850 445]);

    add_block('simulink/Math Operations/Sum', [ctrl '/Tracking error'], ...
        'Inputs', '+-', 'Position', [90 50 125 85]);
    add_block('simulink/Discrete/Unit Delay', [ctrl '/e_prev'], ...
        'InitialCondition', '0', 'SampleTime', T, ...
        'Position', [180 105 230 145]);
    add_block('simulink/Discrete/Unit Delay', [ctrl '/e_prev2'], ...
        'InitialCondition', '0', 'SampleTime', T, ...
        'Position', [260 105 310 145]);
    add_block('simulink/Discrete/Unit Delay', [ctrl '/y_prev1'], ...
        'InitialCondition', '0', 'SampleTime', T, ...
        'Position', [170 185 220 225]);
    add_block('simulink/Discrete/Unit Delay', [ctrl '/y_prev2'], ...
        'InitialCondition', '0', 'SampleTime', T, ...
        'Position', [250 185 300 225]);
    add_block('simulink/Discrete/Unit Delay', [ctrl '/u_prev1'], ...
        'InitialCondition', '0', 'SampleTime', T, ...
        'Position', [690 120 740 160]);
    add_block('simulink/Discrete/Unit Delay', [ctrl '/u_prev2'], ...
        'InitialCondition', '0', 'SampleTime', T, ...
        'Position', [690 185 740 225]);

    add_block('simulink/Sources/Constant', [ctrl '/alpha'], ...
        'Value', num(p.alpha), 'Position', [235 405 285 435]);
    add_block('simulink/Sources/Constant', [ctrl '/q0'], ...
        'Value', num(p.q0), 'Position', [495 345 545 375]);
    add_block('simulink/Sources/Constant', [ctrl '/q1'], ...
        'Value', num(p.q1), 'Position', [495 395 545 425]);
    add_block('simulink/Sources/Constant', [ctrl '/q2'], ...
        'Value', num(p.q2), 'Position', [495 445 545 475]);
    add_block('simulink/Sources/Constant', [ctrl '/q3'], ...
        'Value', num(p.q3), 'Position', [495 495 545 525]);
    add_block('simulink/Sources/Constant', [ctrl '/kFreeze'], ...
        'Value', num(p.kFreeze), 'Position', [495 545 545 575]);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [ctrl '/RLS Estimator'], 'Position', [340 205 460 335]);
    setFunctionScript([ctrl '/RLS Estimator'], rlsScript(p));

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [ctrl '/Pole placement'], 'Position', [585 245 705 365]);
    setFunctionScript([ctrl '/Pole placement'], polePlacementScript());

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [ctrl '/RST law'], 'Position', [475 40 600 140]);
    setFunctionScript([ctrl '/RST law'], [ ...
        "function u = rst_law(c0,d2,d1,d0,e,e1,e2,u1,u2)" newline ...
        "%#codegen" newline ...
        "% Gc(z)=D(z)/((z-1)(z+c0)); divide by z^2 to obtain this recursion." newline ...
        "u = u1 - c0 * (u1 - u2) + d2 * e + d1 * e1 + d0 * e2;" newline ...
        "end"]);

    add_block('simulink/Discontinuities/Saturation', [ctrl '/Voltage saturation'], ...
        'UpperLimit', num(p.uMax), 'LowerLimit', num(-p.uMax), ...
        'Position', [635 50 700 90]);

    add_line(ctrl, 'reference/1', 'Tracking error/1', 'autorouting', 'on');
    add_line(ctrl, 'speed/1', 'Tracking error/2', 'autorouting', 'on');
    add_line(ctrl, 'Tracking error/1', 'e_prev/1', 'autorouting', 'on');
    add_line(ctrl, 'e_prev/1', 'e_prev2/1', 'autorouting', 'on');
    add_line(ctrl, 'Tracking error/1', 'RST law/5', 'autorouting', 'on');
    add_line(ctrl, 'e_prev/1', 'RST law/6', 'autorouting', 'on');
    add_line(ctrl, 'e_prev2/1', 'RST law/7', 'autorouting', 'on');
    add_line(ctrl, 'speed/1', 'y_prev1/1', 'autorouting', 'on');
    add_line(ctrl, 'y_prev1/1', 'y_prev2/1', 'autorouting', 'on');

    add_line(ctrl, 'speed/1', 'RLS Estimator/1', 'autorouting', 'on');
    add_line(ctrl, 'y_prev1/1', 'RLS Estimator/2', 'autorouting', 'on');
    add_line(ctrl, 'y_prev2/1', 'RLS Estimator/3', 'autorouting', 'on');
    add_line(ctrl, 'u_prev1/1', 'RLS Estimator/4', 'autorouting', 'on');
    add_line(ctrl, 'u_prev2/1', 'RLS Estimator/5', 'autorouting', 'on');
    add_line(ctrl, 'alpha/1', 'RLS Estimator/6', 'autorouting', 'on');

    add_line(ctrl, 'RLS Estimator/1', 'Pole placement/1', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/2', 'Pole placement/2', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/3', 'Pole placement/3', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/4', 'Pole placement/4', 'autorouting', 'on');
    add_line(ctrl, 'q0/1', 'Pole placement/5', 'autorouting', 'on');
    add_line(ctrl, 'q1/1', 'Pole placement/6', 'autorouting', 'on');
    add_line(ctrl, 'q2/1', 'Pole placement/7', 'autorouting', 'on');
    add_line(ctrl, 'q3/1', 'Pole placement/8', 'autorouting', 'on');
    add_line(ctrl, 'kFreeze/1', 'Pole placement/9', 'autorouting', 'on');

    add_line(ctrl, 'Pole placement/1', 'RST law/1', 'autorouting', 'on');
    add_line(ctrl, 'Pole placement/2', 'RST law/2', 'autorouting', 'on');
    add_line(ctrl, 'Pole placement/3', 'RST law/3', 'autorouting', 'on');
    add_line(ctrl, 'Pole placement/4', 'RST law/4', 'autorouting', 'on');
    add_line(ctrl, 'u_prev1/1', 'RST law/8', 'autorouting', 'on');
    add_line(ctrl, 'u_prev2/1', 'RST law/9', 'autorouting', 'on');
    add_line(ctrl, 'RST law/1', 'Voltage saturation/1', 'autorouting', 'on');
    add_line(ctrl, 'Voltage saturation/1', 'u_prev1/1', 'autorouting', 'on');
    add_line(ctrl, 'u_prev1/1', 'u_prev2/1', 'autorouting', 'on');
    add_line(ctrl, 'Voltage saturation/1', 'u_sat/1', 'autorouting', 'on');

    add_line(ctrl, 'RLS Estimator/1', 'a1_est/1', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/2', 'a0_est/1', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/3', 'b1_est/1', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/4', 'b0_est/1', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/5', 'traceP/1', 'autorouting', 'on');
end

%% ---------------------------------------------------------- block scripts
function code = rlsScript(p)
    code = [ ...
        "function [a1_est,a0_est,b1_est,b0_est,traceP] = rls_estimator(y,y1,y2,u1,u2,alpha)" newline ...
        "%#codegen" newline ...
        "% RLS for y(k) = [-y(k-1), -y(k-2), u(k-1), u(k-2)] * theta." newline ...
        "% Use alpha = 1 here; alpha < 1 without persistent excitation causes covariance windup and bursting." newline ...
        "% The excitation gate skips idle updates, and the trace limit is a final guard." newline ...
        "persistent P theta" newline ...
        "if isempty(P)" newline ...
        "    P = " num(p.P0) " * eye(4);" newline ...
        "    theta = [-1.0; 0.2; 0.05; 0.02];" newline ...
        "end" newline ...
        "phi = [-y1; -y2; u1; u2];" newline ...
        "if (phi' * phi) > 1e-8" newline ...
        "    den = phi' * P * phi + alpha;" newline ...
        "    L = (P * phi) / den;" newline ...
        "    thetaNew = theta + L * (y - phi' * theta);" newline ...
        "    PNew = (eye(4) - L * phi') * P / alpha;" newline ...
        "    PNew = 0.5 * (PNew + PNew');" newline ...
        "    trNew = trace(PNew);" newline ...
        "    if isfinite(trNew) && all(isfinite(thetaNew))" newline ...
        "        theta = thetaNew;" newline ...
        "        P = PNew;" newline ...
        "    end" newline ...
        "end" newline ...
        "tr = trace(P);" newline ...
        "if tr > " num(p.tracePLimit) newline ...
        "    P = P * (" num(p.tracePLimit) " / tr);" newline ...
        "    tr = trace(P);" newline ...
        "end" newline ...
        "a1_est = theta(1);" newline ...
        "a0_est = theta(2);" newline ...
        "b1_est = theta(3);" newline ...
        "b0_est = theta(4);" newline ...
        "traceP = tr;" newline ...
        "end"];
end

function code = polePlacementScript()
    code = [ ...
        "function [c0,d2,d1,d0] = pole_placement(a1,a0,b1,b0,q0,q1,q2,q3,kFreeze)" newline ...
        "%#codegen" newline ...
        "% From (z^2+a1*z+a0)(z-1)(z+c0) +" newline ...
        "% (b1*z+b0)(d2*z^2+d1*z+d0) = z^4+q3*z^3+q2*z^2+q1*z+q0." newline ...
        "% Matching z^3..z^0 coefficients gives M*[c0; d2; d1; d0] = rhs." newline ...
        "persistent c0Hold d2Hold d1Hold d0Hold k" newline ...
        "if isempty(k)" newline ...
        "    c0Hold = 0.0;" newline ...
        "    d2Hold = 0.2;" newline ...
        "    d1Hold = 0.0;" newline ...
        "    d0Hold = 0.0;" newline ...
        "    k = 0.0;" newline ...
        "end" newline ...
        "if k >= kFreeze" newline ...
        "    M = [1.0,     b1, 0.0, 0.0;" newline ...
        "         a1-1.0,  b0, b1,  0.0;" newline ...
        "         a0-a1,  0.0, b0,  b1;" newline ...
        "        -a0,     0.0, 0.0, b0];" newline ...
        "    rhs = [q3 - a1 + 1.0; q2 - a0 + a1; q1 + a0; q0];" newline ...
        "    if rcond(M) >= 1e-8" newline ...
        "        sol = M \ rhs;" newline ...
        "        if all(isfinite(sol))" newline ...
        "            c0Hold = sol(1);" newline ...
        "            d2Hold = sol(2);" newline ...
        "            d1Hold = sol(3);" newline ...
        "            d0Hold = sol(4);" newline ...
        "        end" newline ...
        "    end" newline ...
        "end" newline ...
        "k = k + 1.0;" newline ...
        "c0 = c0Hold;" newline ...
        "d2 = d2Hold;" newline ...
        "d1 = d1Hold;" newline ...
        "d0 = d0Hold;" newline ...
        "end"];
end

%% ---------------------------------------------------------- local helpers
function setFunctionScript(blockPath, code)
    rt = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
    if isempty(chart), error('MATLAB Function chart not found: %s', blockPath); end
    chart.Script = char(code);
end

function logSignal(blockPath, portNumber, signalName)
    ports = get_param(blockPath, 'PortHandles');
    set_param(ports.Outport(portNumber), 'DataLogging', 'on', ...
        'DataLoggingNameMode', 'Custom', 'DataLoggingName', signalName);
end

function configureScope(scopePath, nAxes, showLegend)
    set_param(scopePath, 'NumInputPorts', num2str(nAxes));
    sc = get_param(scopePath, 'ScopeConfiguration');
    sc.LayoutDimensions = [nAxes 1];
    sc.OpenAtSimulationStart = false;
    sc.ShowLegend = logical(showLegend);
end

function addNote(mdl, text, pos)
    h = Simulink.Annotation(mdl, text);
    h.position = pos;
end
