%% Build a clean, fully discrete adaptive DC-motor simulation.
% Top level: reference -> adaptive controller -> saturated u -> plant.
% The plant is the only subsystem that will later be replaced by ESP32 I/O.

scriptDir = fileparts(mfilename('fullpath'));
run(fullfile(scriptDir, 'adaptive_motor_params.m'));

mdl = 'adaptive_motor_sim';
mdlFile = fullfile(scriptDir, [mdl '.slx']);
if bdIsLoaded(mdl), close_system(mdl, 0); end
new_system(mdl);

set_param(mdl, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', 'T', ...
    'StopTime', 'simTime', ...
    'SignalLogging', 'on', ...
    'SignalLoggingName', 'logsout', ...
    'InitFcn', "run(fullfile(fileparts(get_param(bdroot,'FileName')), 'adaptive_motor_params.m'));", ...
    'Location', [100 100 1550 760]);

%% Top-level blocks
add_block('simulink/Sources/Pulse Generator', [mdl '/Speed reference'], ...
    'PulseType', 'Time based', 'TimeSource', 'Use simulation time', ...
    'Amplitude', 'refAmplitude', 'Period', 'refPeriod', ...
    'PulseWidth', '50', 'PhaseDelay', '0', 'SampleTime', 'T', ...
    'Position', [45 105 105 155]);

ctrl = [mdl '/Adaptive controller'];
add_block('simulink/Ports & Subsystems/Subsystem', ctrl, ...
    'Position', [190 70 410 230]);
Simulink.SubSystem.deleteContents(ctrl);
buildController(ctrl);

add_block('simulink/Sources/Step', [mdl '/Flywheel swap'], ...
    'Time', 'swapTime', 'Before', 'J_small', 'After', 'J_large', ...
    'SampleTime', 'T', 'Position', [510 250 580 290]);

plant = [mdl '/Variable inertia plant'];
add_block('simulink/Ports & Subsystems/Subsystem', plant, ...
    'Position', [570 70 760 210]);
Simulink.SubSystem.deleteContents(plant);
buildPlant(plant);

add_block('simulink/Sources/Random Number', [mdl '/Measurement noise'], ...
    'Mean', '0', 'Variance', 'noiseVariance', 'Seed', 'noiseSeed', ...
    'SampleTime', 'T', 'Position', [620 335 700 375]);
add_block('simulink/Math Operations/Sum', [mdl '/Measured speed'], ...
    'Inputs', '++', 'Position', [830 105 865 155]);

add_block('simulink/Signal Routing/Mux', [mdl '/Tracking mux'], ...
    'Inputs', '3', 'Position', [990 70 995 190]);
add_block('simulink/Sinks/Scope', [mdl '/Tracking scope'], ...
    'Position', [1060 105 1110 155]);
add_block('simulink/Signal Routing/Mux', [mdl '/Adaptation mux'], ...
    'Inputs', '4', 'Position', [990 270 995 410]);
add_block('simulink/Sinks/Scope', [mdl '/Adaptation scope'], ...
    'Position', [1060 315 1110 365]);

%% Top-level wiring
add_line(mdl, 'Speed reference/1', 'Adaptive controller/1', 'autorouting', 'on');
add_line(mdl, 'Adaptive controller/1', 'Variable inertia plant/1', 'autorouting', 'on');
add_line(mdl, 'Flywheel swap/1', 'Variable inertia plant/2', 'autorouting', 'on');
add_line(mdl, 'Variable inertia plant/1', 'Measured speed/1', 'autorouting', 'on');
add_line(mdl, 'Measurement noise/1', 'Measured speed/2', 'autorouting', 'on');
add_line(mdl, 'Measured speed/1', 'Adaptive controller/2', 'autorouting', 'on');

add_line(mdl, 'Speed reference/1', 'Tracking mux/1', 'autorouting', 'on');
add_line(mdl, 'Variable inertia plant/1', 'Tracking mux/2', 'autorouting', 'on');
add_line(mdl, 'Measured speed/1', 'Tracking mux/3', 'autorouting', 'on');
add_line(mdl, 'Tracking mux/1', 'Tracking scope/1', 'autorouting', 'on');

add_line(mdl, 'Adaptive controller/1', 'Adaptation mux/1', 'autorouting', 'on');
add_line(mdl, 'Adaptive controller/2', 'Adaptation mux/2', 'autorouting', 'on');
add_line(mdl, 'Adaptive controller/3', 'Adaptation mux/3', 'autorouting', 'on');
add_line(mdl, 'Flywheel swap/1', 'Adaptation mux/4', 'autorouting', 'on');
add_line(mdl, 'Adaptation mux/1', 'Adaptation scope/1', 'autorouting', 'on');

%% Acceptance-test logging
logSignal([mdl '/Speed reference'], 1, 'ref');
logSignal([mdl '/Variable inertia plant'], 1, 'y_true');
logSignal([mdl '/Measured speed'], 1, 'y');
logSignal([mdl '/Adaptive controller'], 1, 'u');
logSignal([mdl '/Adaptive controller'], 2, 'a0_est');
logSignal([mdl '/Adaptive controller'], 3, 'b0_est');
logSignal([mdl '/Flywheel swap'], 1, 'J');

save_system(mdl, mdlFile);
close_system(mdl, 0);
fprintf('Built %s\n', mdlFile);

%% Subsystem builders
function buildController(ctrl)
    add_block('simulink/Ports & Subsystems/In1', [ctrl '/reference'], ...
        'Port', '1', 'Position', [20 50 50 70]);
    add_block('simulink/Ports & Subsystems/In1', [ctrl '/speed'], ...
        'Port', '2', 'Position', [20 145 50 165]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/u_sat'], ...
        'Port', '1', 'Position', [735 55 765 75]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/a0_est'], ...
        'Port', '2', 'Position', [735 235 765 255]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/b0_est'], ...
        'Port', '3', 'Position', [735 275 765 295]);
    add_block('simulink/Ports & Subsystems/Out1', [ctrl '/error'], ...
        'Port', '4', 'Position', [735 115 765 135]);

    add_block('simulink/Math Operations/Sum', [ctrl '/Tracking error'], ...
        'Inputs', '+-', 'Position', [90 45 125 85]);
    add_block('simulink/Discrete/Unit Delay', [ctrl '/e_prev'], ...
        'InitialCondition', '0', 'SampleTime', 'T', ...
        'Position', [175 100 225 140]);
    add_block('simulink/Discrete/Unit Delay', [ctrl '/y_prev'], ...
        'InitialCondition', '0', 'SampleTime', 'T', ...
        'Position', [175 185 225 225]);
    add_block('simulink/Discrete/Unit Delay', [ctrl '/u_prev'], ...
        'InitialCondition', '0', 'SampleTime', 'T', ...
        'Position', [620 145 670 185]);

    add_block('simulink/Sources/Constant', [ctrl '/alpha'], ...
        'Value', 'alpha', 'Position', [175 315 225 345]);
    add_block('simulink/Sources/Constant', [ctrl '/q0'], ...
        'Value', 'q0', 'Position', [390 335 440 365]);
    add_block('simulink/Sources/Constant', [ctrl '/q1'], ...
        'Value', 'q1', 'Position', [390 375 440 405]);
    add_block('simulink/Sources/Constant', [ctrl '/b0 guard'], ...
        'Value', 'b0Min', 'Position', [390 415 440 445]);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [ctrl '/RLS Estimator'], 'Position', [270 195 390 305]);
    setFunctionScript([ctrl '/RLS Estimator'], [
        "function [a0_est,b0_est] = rls_estimator(y_curr,y_prev,u_prev,alpha)" newline ...
        "%#codegen" newline ...
        "persistent P xe" newline ...
        "if isempty(P)" newline ...
        "    P = 100.0 * eye(2);" newline ...
        "    xe = [-0.5; 1.0];" newline ...
        "end" newline ...
        "C = [-y_prev, u_prev];" newline ...
        "den = C * P * C' + alpha;" newline ...
        "L = (P * C') / den;" newline ...
        "xe = xe + L * (y_curr - C * xe);" newline ...
        "P = (eye(2) - L * C) * P / alpha;" newline ...
        "P = 0.5 * (P + P');" newline ...
        "a0_est = xe(1);" newline ...
        "b0_est = xe(2);" newline ...
        "end"]);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [ctrl '/Pole placement'], 'Position', [475 205 590 315]);
    setFunctionScript([ctrl '/Pole placement'], [
        "function [d0,d1] = pole_placement(a0,b0,q0,q1,b0Min)" newline ...
        "%#codegen" newline ...
        "persistent d0Hold d1Hold" newline ...
        "if isempty(d0Hold)" newline ...
        "    d0Hold = -0.44;" newline ...
        "    d1Hold = 1.0;" newline ...
        "end" newline ...
        "if abs(b0) > b0Min" newline ...
        "    d0Hold = (q0 + a0) / b0;" newline ...
        "    d1Hold = (q1 + 1.0 - a0) / b0;" newline ...
        "end" newline ...
        "d0 = d0Hold;" newline ...
        "d1 = d1Hold;" newline ...
        "end"]);

    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [ctrl '/Incremental PI'], 'Position', [420 35 555 145]);
    setFunctionScript([ctrl '/Incremental PI'], [
        "function u = incremental_pi(d0,d1,e,ePrev,uPrev)" newline ...
        "%#codegen" newline ...
        "u = uPrev + d1 * e + d0 * ePrev;" newline ...
        "end"]);
    add_block('simulink/Discontinuities/Saturation', [ctrl '/PWM saturation'], ...
        'UpperLimit', 'uMax', 'LowerLimit', 'uMin', ...
        'Position', [610 45 675 85]);

    add_line(ctrl, 'reference/1', 'Tracking error/1', 'autorouting', 'on');
    add_line(ctrl, 'speed/1', 'Tracking error/2', 'autorouting', 'on');
    add_line(ctrl, 'Tracking error/1', 'e_prev/1', 'autorouting', 'on');
    add_line(ctrl, 'Tracking error/1', 'Incremental PI/3', 'autorouting', 'on');
    add_line(ctrl, 'Tracking error/1', 'error/1', 'autorouting', 'on');
    add_line(ctrl, 'speed/1', 'y_prev/1', 'autorouting', 'on');
    add_line(ctrl, 'speed/1', 'RLS Estimator/1', 'autorouting', 'on');
    add_line(ctrl, 'y_prev/1', 'RLS Estimator/2', 'autorouting', 'on');
    add_line(ctrl, 'u_prev/1', 'RLS Estimator/3', 'autorouting', 'on');
    add_line(ctrl, 'alpha/1', 'RLS Estimator/4', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/1', 'Pole placement/1', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/1', 'a0_est/1', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/2', 'Pole placement/2', 'autorouting', 'on');
    add_line(ctrl, 'RLS Estimator/2', 'b0_est/1', 'autorouting', 'on');
    add_line(ctrl, 'q0/1', 'Pole placement/3', 'autorouting', 'on');
    add_line(ctrl, 'q1/1', 'Pole placement/4', 'autorouting', 'on');
    add_line(ctrl, 'b0 guard/1', 'Pole placement/5', 'autorouting', 'on');
    add_line(ctrl, 'Pole placement/1', 'Incremental PI/1', 'autorouting', 'on');
    add_line(ctrl, 'Pole placement/2', 'Incremental PI/2', 'autorouting', 'on');
    add_line(ctrl, 'e_prev/1', 'Incremental PI/4', 'autorouting', 'on');
    add_line(ctrl, 'u_prev/1', 'Incremental PI/5', 'autorouting', 'on');
    add_line(ctrl, 'Incremental PI/1', 'PWM saturation/1', 'autorouting', 'on');
    add_line(ctrl, 'PWM saturation/1', 'u_prev/1', 'autorouting', 'on');
    add_line(ctrl, 'PWM saturation/1', 'u_sat/1', 'autorouting', 'on');
end

function buildPlant(plant)
    add_block('simulink/Ports & Subsystems/In1', [plant '/u'], ...
        'Port', '1', 'Position', [25 55 55 75]);
    add_block('simulink/Ports & Subsystems/In1', [plant '/J'], ...
        'Port', '2', 'Position', [25 155 55 175]);
    add_block('simulink/Ports & Subsystems/Out1', [plant '/omega'], ...
        'Position', [545 55 575 75]);
    add_block('simulink/Discrete/Unit Delay', [plant '/omega state'], ...
        'InitialCondition', '0', 'SampleTime', 'T', ...
        'Position', [440 45 490 85]);
    add_block('simulink/Sources/Constant', [plant '/minus bT'], ...
        'Value', '-b*T', 'Position', [80 215 135 245]);
    add_block('simulink/Math Operations/Product', [plant '/divide by J'], ...
        'Inputs', '*/', 'Position', [175 165 220 210]);
    add_block('simulink/Math Operations/Math Function', [plant '/exp'], ...
        'Operator', 'exp', 'Position', [255 170 305 205]);
    add_block('simulink/Sources/Constant', [plant '/one'], ...
        'Value', '1', 'Position', [250 250 290 280]);
    add_block('simulink/Math Operations/Sum', [plant '/one minus A'], ...
        'Inputs', '+-', 'Position', [335 215 370 265]);
    add_block('simulink/Math Operations/Gain', [plant '/Km over b'], ...
        'Gain', 'Km/b', 'Position', [400 220 445 260]);
    add_block('simulink/Math Operations/Product', [plant '/A times omega'], ...
        'Position', [335 70 375 110]);
    add_block('simulink/Math Operations/Product', [plant '/B times u'], ...
        'Position', [335 135 375 175]);
    add_block('simulink/Math Operations/Sum', [plant '/state update'], ...
        'Inputs', '++', 'Position', [405 110 435 170]);

    add_line(plant, 'J/1', 'divide by J/2', 'autorouting', 'on');
    add_line(plant, 'minus bT/1', 'divide by J/1', 'autorouting', 'on');
    add_line(plant, 'divide by J/1', 'exp/1', 'autorouting', 'on');
    add_line(plant, 'exp/1', 'one minus A/2', 'autorouting', 'on');
    add_line(plant, 'one/1', 'one minus A/1', 'autorouting', 'on');
    add_line(plant, 'one minus A/1', 'Km over b/1', 'autorouting', 'on');
    add_line(plant, 'exp/1', 'A times omega/1', 'autorouting', 'on');
    add_line(plant, 'omega state/1', 'A times omega/2', 'autorouting', 'on');
    add_line(plant, 'Km over b/1', 'B times u/1', 'autorouting', 'on');
    add_line(plant, 'u/1', 'B times u/2', 'autorouting', 'on');
    add_line(plant, 'A times omega/1', 'state update/1', 'autorouting', 'on');
    add_line(plant, 'B times u/1', 'state update/2', 'autorouting', 'on');
    add_line(plant, 'state update/1', 'omega state/1', 'autorouting', 'on');
    add_line(plant, 'omega state/1', 'omega/1', 'autorouting', 'on');
end

%% Local helpers
function setFunctionScript(blockPath, code)
    rt = sfroot;
    chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
    if isempty(chart), error('MATLAB Function chart not found: %s', blockPath); end
    chart.Script = char(code);
end

function logSignal(blockPath, portNumber, signalName)
    ports = get_param(blockPath, 'PortHandles');
    set_param(ports.Outport(portNumber), 'DataLogging', 'on', ...
        'DataLoggingNameMode', 'Custom', 'DataLoggingName', signalName);
end
